theme: striped

site:
  url: http://prettystack.github.io/jekyll-blog-starter
  name: DonQuiblog
  description: Performant Assemble.io blog starter
  build: dist/

menus:
  - name: Home
    url: /

  - name: About
    url: /about.html

  - name: Contact
    url: /contact.html

# Disqus configuration, comment these lines to disable it
disqus:
  shortname: donquiblog

# Google analytics
ga: UA-XXXXXXXX-X