# Theme name.
theme: striped

# site globals
site:
  url: http://prettystack.github.io/jekyll-blog-starter
  name: DonQuiblog
  description: Performant Assemble.io blog starter
  build: dist/

# Main menu
menus:
  - name: Home
    url: /

  - name: About
    url: /about.html

  - name: Contact
    url: /contact.html

# Disqus configuration, comment these lines to disable it
disqus:
  shortname: donquiblog

google:
  analytics: UA-49342017-1 # Google analytics
  verification: "mLz0EXywn-dwnrN2y6nCZRlSvFTIm61gwANPbK0o2Uk" # Google webmaster verification
